tasks:
  - name: pull container images
    init: |
      # install container images
      docker-compose pull
    command: |
      gp open README.md
      export PUBLIC_IP=127.0.0.1
      docker-compose up 
  - name: Install PGCLI  
    init: |
      pip install -U pgcli 
    command: 
      # run postgresql client pgcli and connect to demodb as user demo; wait 30 seconds to be sure that database container is running
      sleep 30s && pgcli 'postgres://demo:abc123!@localhost:5432/demodb'
   
ports:

  # PostgreSQL
  - port: 5432
    visibility: private

  # NocoDB
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker    